services:
  postgres:
    image: postgres:16-alpine
    container_name: retail_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-retail_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Retail123!}
      POSTGRES_DB: ${POSTGRES_DB:-retail_db}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01_infra/postgres/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-retail_admin} -d ${POSTGRES_DB:-retail_db}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
    driver: local
